[package]
name = "test-todomvc-backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
worker = ["dep:worker", "dep:worker-macros"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "js"] }
worker = { version = "0.5", features = ["d1"], optional = true }
worker-macros = { version = "0.5", optional = true }

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
